### ISSUE TITLE
Accessibility out of scope?

### ISSUE THREAD

**Issue by alice** [immersive-web/dom-overlays#32]
Coming here from the [TAG review thread](https://github.com/w3ctag/design-reviews/issues/470), as we are looking at this at our virtual face-to-face.

I was a little taken aback at the comment that the overlaid interface would help with internationalisation and accessibility, but that accessibility is out of scope.

- Could you elaborate on why accessibility is out of scope, if it is worth mentioning as a benefit? 
- How do you envisage accessibility benefiting from this API?

**Comment by klausw** [comment]
I wasn't sure how to answer the accessibility scope question. The DOM overlays API itself is fairly minimal and doesn't expose new user-facing features that would need new accessibility considerations. There aren't any new user-visible dialogs or interactive elements provided as part of the DOM overlays API itself.

However, it does make already existing platform features available in a new context, and makes it possible to use existing web accessibility features for immersive applications too.

As a specific example, enabling "talkback" mode on an Android phone changes the way that platform UIs work. Screen touches result in the touched text or UI element being read aloud or described by voice output. This already works for 2D web content in the browser, but a normal WebXR application wouldn't have been able to make direct use of this since there wasn't any available information about screen content usable by this system feature.

When showing a DOM overlay on top of WebXR content, the existing "talkback" functionality now works for this DOM content. For example, if the application shows an "Exit AR" button, this button can now be discovered by touch and activated by double-tapping it when talkback is enabled. For more complex UI such as dialogs or explanatory text, this information is fully accessible without requiring any extra work by the application developer.

Of course, fully accessible applications will still require significant effort by the application developer, and some have started to work on this, for example <model-viewer> supports spoken descriptions of scene views, but this becomes easier with DOM overlays, for example when used for text annotations.

If you have an ARCore-compatible Android phone, you can try this on https://modelviewer.dev/examples/annotations.html using Chrome Beta (or Dev/Canary, as long as it's >= version 83). You can configure TalkBack in Android system "accessibility" settings, and set the "Volume Up + Volume Down" key combination as a toggle for that featur.

**Comment by klausw** [comment]
I've rephrased this in the explainer, removing the "beyond the scope" part and clarified that the goal is to let UAs leverage existing DOM accessibility features.
