### ISSUE TITLE
Configuring the active DOM element for the overlay

### ISSUE THREAD

**Issue by klausw** [immersive-web/dom-overlays#5]
The current [sample implementation](https://github.com/immersive-web/dom-overlays/blob/master/explainer.md#sample-implementation) uses a feature descriptor named "dom-overlay-for-handheld-ar" for enabling DOM overlay mode, but does not specify a DOM element at session creation time. By default, the DOM overlay shows the `<body>` element, and applications can use the Fullscreen API to change the element while the session is active.

Going forward, would it be preferable to explicitly declare at session creation time which DOM element is to be used for the overlay? 

This would potentially be a use case for a feature descriptor with attributes, i.e. something like this:

```js
let elem = document.getElementById('content');
navigator.xr.requestSession(‘immersive-ar’,
   {optionalFeatures: [
     new XRDOMOverlayForHandheldAR({overlayElement: elem}) 
   ]});
```

However, as far as I know there isn't yet a clear consensus how non-enum feature attributes should be declared, see for example ongoing discussions in https://github.com/immersive-web/webxr/issues/860, and previous discussions in https://github.com/immersive-web/webxr/issues/791 that mention a XRFeatureInit class. [This comment](https://github.com/immersive-web/webxr/issues/791#issuecomment-519602728) by toji@ uses `new XRMinimumBoundsRequirement(3, 2)` as an example.

Alternatively, should there be a separate API such an XRSession `setDOMOverlayElement(elem)` method for configuring this? That seems more heavyweight and invasive though.

Is there a need to be able to change the fullscreened element at runtime, or is it good enough to specify an element at session start? The application would always be able to use DOM manipulation to move nodes in and out of that element as needed, or use CSS visibility rules.

Note that if there is a DOM overlay specific way to specify the overlay element, there's still some overlap with the Fullscreen API. Some implementations may be using similar mechanisms for DOM overlay and fullscreen mode and may not be able to change them separately. To avoid incompatibility, it may be worth specifying that using the fullscreen API while in DOM overlay mode is either prohibited or results in undefined behavior. Alternatively, if the requirement is that both work independently, this could be an additional burden on implementations.

**Comment by klausw** [comment]
@NellWaliczek @mounirlamouri See ^^^, let me know if you have feedback or additional suggestions on this.

**Comment by mounirlamouri** [comment]
I would have a preference for:
```javascript
partial dictionary XRSessionInit {
  HTMLElement overlayRoot;
};
```

Alternatively:
```javascript
partial dictionary XRSessionInit {
  OverlayInit overlay;
};

dictionary OveralyInit {
  HTMLElement root;
};
```

This way, it disassociate the feature request from the init options as the init options have nothing to do with the feature request.

**Comment by klausw** [comment]
@mounirlamouri I'm fine with that approach. To avoid potential namespace collisions, would it be useful to establish a convention that additional fields added to XRSessionInit (or other shared objects) should use a naming prefix based on the feature name that enables them? For example:

```webidl
partial dictionary XRSessionInit {
  DOMOverlayInit domOverlay;
};

dictionary DOMOverlayInit {
  HTMLElement overlayElement;
};
```

(Currently, the feature name is `dom-overlay-for-handheld-ar`, but using that as a name prefix would be rather clunky. The examples above use a shortened prefix, but I also filed issue #6 to see separately if it would make sense to just shorten the feature name.)

**Comment by mounirlamouri** [comment]
Prefixing with the feature or module name lgtm!

**Comment by blairmacintyre** [comment]
(picking this thread up)

Where did this end up?  I'd very much like this to be resolved in the proposal.  Having the `<body>` element go fullscreen makes this a bit more fragile when implementing AR in a polyfill (for example), and my expectation (based on all the feedback people have given on their work with both Argon and WebXR Viewer over the last decade) is that having the overlay UI separate from the non-immersive UI is more convenient in practice.  For apps (like many of our demos) that have a full-screen `inline` canvas with some UI, that switches to AR on button press, using `<body>` seems convenient.  But for more complex apps, that would have the `inline` element in a page that scrolls and has other content (e.g., a shopping app, or "fix your own printer" app), just having a single element go fullscreen, where the developer can inject content, seems more convenient.

That said, I'm ok with both the "provide the element during session creation" or the "session method to set the element".  I'd have a slight preference for the former, because (as @klausw says) I don't see any great need to swap elements at runtime.  If I was designing an app that wanted to swap the UI at runtime, I'd have those UIs in another set of divs, and swap those divs in and out of the HUD div.   

I'd also prefer there was no default and it had to be explicitly specified.

**Comment by klausw** [comment]
Based on discussions in the group, the element now needs to be supplied as part of the session init options, and there is no default. The session is rejected with NotSupportedError if the needed element wasn't supplied. The current draft spec at https://immersive-web.github.io/dom-overlays/#xrsessioninit documents it that way.

(This doesn't yet match the prototype Chrome implementation, I'm currently working on updating that.)
