### ISSUE TITLE
Request for Examples

### ISSUE THREAD

**Issue by raviramachandra** [immersive-web/dom-overlays#8]
Can we have a hello world DOM Overlay example ?

**Comment by klausw** [comment]
Yes, we need to add these, I'm currently working on examples matching the proposed spec. 

In the meantime, I have some simple examples that originally worked with the older prototype API as currently implemented in Chrome, but I've added support for the proposed spec's API also. This isn't ideal as a reference due to the mix of APIs, but may be useful for testing:

* https://klausw.github.io/three.js/examples/webvr_lorenzattractor.html - floating lorenz attractor with a simple GUI to change parameters interactively. Doesn't use any XR input.
* https://klausw.github.io/a-frame-car-sample/index.html - A-Frame based remote control car, using XR controllers where available, and an optional DOM Overlay making a screen joystick usable in AR mode. This example was mainly intended as an experiment for cross-form-factor compatibility from desktop 6DoF VR to handheld AR, and I'd be curious to know how well it works on an AR headset.

**Comment by klausw** [comment]
The examples at https://storage.googleapis.com/chromium-webxr-test/latest.html?target=proposals/index.html now include DOM Overlay support for "AR Hit Test" and "AR Plane Detection & Anchors", including a visualization of XR input events when using [this link](https://storage.googleapis.com/chromium-webxr-test/latest.html?target=proposals/phone-ar-hit-test.html?debugSources=true%26iframe=true).

These are intended to exercise the recently updated APIs as of Chrome Canary 81.0.4029.2 which should match the current [draft spec](https://immersive-web.github.io/dom-overlays/), and won't work as expected on older Chrome versions.

(The two examples from my [previous comment](https://github.com/immersive-web/dom-overlays/issues/8#issuecomment-572739206) should continue to work, though they have some backwards compatibility code as well to work with the previous API.)

I'll keep this issue open since I think it would still be useful to have a very basic standalone example.

**Comment by klausw** [comment]
I modified the "XR barebones" sample to work with AR mode and an optional DOM Overlay.

Live: https://storage.googleapis.com/chromium-webxr-test/latest.html?target=proposals/ar-barebones-dom-overlay.html

Source: https://cs.chromium.org/chromium/src/third_party/webxr_test_pages/webxr-samples/proposals/ar-barebones-dom-overlay.html

@toji - as a more general question, how would you feel about adding some basic AR samples such as this one on https://immersive-web.github.io/webxr-samples/ ? The current "proposals/" directory is a bit confusing, it started out as tests for inline AR on phones and the names reflect that, while they are actually using "immersive-ar" and could also work on AR headsets. Maybe delete ones using less-stable APIs (they aren't actively maintained at that location and likely don't currently work), but keep some basic ones using reasonably-stable APIs?

**Comment by toji** [comment]
I'd be happy to move the this sample and the rest of the AR samples to the main samples page, since they have definitely moved beyond what I had envisioned the proposals directory to be used for.
